Jedlueng 
19 October 2022 

```{r}
data("PimaIndiansDiabetes")
head(PimaIndiansDiabetes)
df <- PimaIndiansDiabetes
```



```{r}
glimpse(df)
```



#1. Split Data 
```{r}
set.seed(42)
id <- createDataPartition( y = df$diabetes,
                           p = 0.8, 
                           list = FALSE)

train_df <- df[id, ]
test_df <- df[-id, ]
```



#2. Train model 
```{r}
set.seed(99)
tree_model <- train(diabetes ~., 
                    data = train_df,
                    method = "rpart",
                    trControl = trainControl(method = "cv",
                                             number = 5))

print(tree_model)
```


#Decision Tree with Customize Grid 
```{r}

myGrid <- data.frame(cp = seq(0.001, 0.3, by = 0.005))

tree_model <- train(diabetes ~.,
                    data = train_df ,
                    method = "rpart",
                    tuneGrid = myGrid,
                    trControl = trainControl(method = "cv", number =5 ))
print(tree_model)
tree_model$finalModel
```

#Visiaulziation 

```{r}
library(rpart.plot)


rpart.plot(tree_model$finalModel)
```



